apiVersion: apps/v1
kind: Deployment
metadata:
  name: Deployment
  labels:
    app: Deployment
  namespace: namespace-workflow-bosch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Deployment
  template:
    metadata:
      labels:
        app: Deployment
    spec:
      containers:
        - name: Deployment
          image: conacr.azurecr.io/image-workflow-bosch:latest
          ports:
            - containerPort: 3000
