apiVersion: v1
kind: Service
metadata:
  name: Deployment
  namespace: boschnamespace
spec:
  type: LoadBalancer
  selector:
    app: Deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
