apiVersion: v1
kind: Service
metadata:
  name: Deployment
  namespace: image-workflow-1693495803035
spec:
  type: LoadBalancer
  selector:
    app: Deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
